### PR TITLE
Db/custom fetch

### PR DESCRIPTION
**Pull request by flamenaak**
Hey,
your library is a very nice piece of work and my team and other teams at workplace would like to use it. However we have our own function which wraps window.fetch that we have to use. But it doesn t look like that can be achieved using the current fetch component.
So I added a fetch function prop (defaulting to native fetch) which can specify function that is called to fetch data.
I also added a test making sure the custom fetch functoin is called when the component is created.

Best regards

### CODE REVIEW

**Comment by techniq** [comment]
Thanks for the praise, and I appreciate it and your contribution.

I've been thinking about how allow a user to perform their own fetching, both directly to override (like in your case), or to enable debouncing/throttling of requests (see #6).  I think your PR could support of these use cases, but could you possibly create a test to show how to debounce use the prop as well?  I'm also not 100% sold on `fetchFunction`, but I might come around to it.  Originally I was thinking of something like `onRequest`, but that might not be descriptive.

**Comment by flamenaak** [comment]
Thanks for a quick answer.
I ve attempted to write a test simulating multiple calls of fetch and debounce them. Right now the tests passes and seem reasonable to me.
However I m not very experienced at async testing and maybe on or little above intermeddiate level of javascript.
I appreciate any advice or commentary to the code.
I called prop a fetchFunction because it is called instead of the fetch() and should have sa signature, maybe onRequest is something different in your mind? Also in the end we will probably have to make our own component, because our response might not be same as one from fetch()

**Comment by techniq** [comment]
@flamenaak Thanks for this.  I [reworked](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L494) the debounce test/example to resolve all the promises (including the skipped/debounced calls) with the response of the last one so we don't keep unresolved promises forever.

In retrospect, it's probably best to debounce outside of the fetch call (and preferable outside of `<Fetch />` such as using something like [<Debounce>](https://github.com/threepointone/react-debounce)) as while we won't make multiple fetch/network calls, we are still rendering for each call (for loading and the data, although the data will all come from the same/only/last response).

Anyways, this is getting off topic for this issue.  I've release 5.1.0 with the new `fetchFunction` prop.

Btw, you mentioned about creating your own component.  A common pattern I use is to wrap `<Fetch />` in your own component, such as `<UserData/>`.  [react-odata](https://github.com/techniq/react-odata/blob/master/src/OData.js) actually does this as well to be used specifically for OData requests.  You can also create [middleware/interceptors](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L1327) to handle things.  I really need to improve the documentation (i.e. create something more than just the README) to show all the different possibilities you can do with this library.  Currently looking at the tests is one of the best ways right now.  The examples in my [mui-downshift](https://github.com/techniq/mui-downshift/blob/master/stories/fetch.js) can also be useful, which shows how to create a `<MockFetch />` component for testing, implement infinite scrolling and pagination with `onDataChange` and react-virtualized, and a few others.

**Comment by flamenaak** [comment]
@techniq
 You are most welcome. I thank you for the opportunity, this is my first contribution to a public library.
Thanks for the tip in the last paragraph as well.
Good luck

**Pull request merged**
