### PR TITLE
Only retain successful responses in cache

### PR DESCRIPTION
**Pull request by davin-english**
#14 
* Added ability to remove entry from SimpleCache when fetch call fails

### CODE REVIEW

**Comment by davin-english** [comment]
#14

**Comment by davin-english** [comment]
Let me know if you'd like me to write Fetch.test.js tests as well. I started to, but then the tests in Fetch.test.js and SimpleCache.test.js started to look very similar, if not basically the same. I suppose I could write a Fetch test that ensures a 2nd call is made because the first one failed and isn't in the cache.

**Comment by techniq** [comment]
@davin-english I see you calling `await fetchMock.flush();` in the `SimpleCache` tests but not actually mocking.  Is this needed for a reason I'm overlooking?

**Comment by davin-english** [comment]
@techniq, yeah if I remove the await, the .then callback in SimpleCache doesn't return in time for the test to actually do its checks

**Comment by techniq** [comment]
Could you await the promise results from the cache.

From
```js
const promiseAfter = cache.get(URL);
```
To
```js
const results = await cache.get(URL);
```

**Comment by techniq** [comment]
You can also using `expect(...).resolves.toBe(...))` - https://facebook.github.io/jest/docs/en/expect.html#resolves

**Comment by techniq** [comment]
@davin-english No worries and thanks for the PR and digging in.  I just released this as `6.0.1` if you want to pull it and let me know how it goes.

**Comment by davin-english** [comment]
@techniq thanks a lot! I'll test this out tomorrow.

**Comment by davin-english** [comment]
@techniq Nope, I lied. I just tested out a few minutes ago. Works like a charm!

**Pull request merged**
