### PR TITLE
Upgrade React to 16

### PR DESCRIPTION
**Pull request by aaronjensen**
Thanks for the nice component!

### CODE REVIEW

**Comment by aaronjensen** [comment]
More is necessary for this, working on it...

**Comment by aaronjensen** [comment]
Ok, this should be ready to go now.

**Comment by techniq** [comment]
@aaronjensen Thanks for this.  I haven't had time to play with React 16 yet but plan to very soon.  I'll try to merge this hopefully tonight but worst case in the next few days.  I know most of the changes are on the non-library side (error boundaries, etc).  Have you seen anything regarding libraries beyond the version bumps (enzyme needing 3+, etc)

**Comment by aaronjensen** [comment]
@techniq No problem. I haven't heard anything, no. I just added another fix for a warning that's new in 16, but that's all I know for now.

**Comment by techniq** [comment]
@aaronjensen thanks again.  I released this as 5.0.0 (just to be safe)

**Pull request merged**
